app:
  title: CDCR Development Portal
  baseUrl: https://backstage.cdcr.ca.gov

backend:
  baseUrl: https://backstage.cdcr.ca.gov
  listen:
    port: 7007
    host: 0.0.0.0
  
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: backstage_plugin_catalog

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - name: dev
          url: ${KUBERNETES_DEV_URL}
          authProvider: 'serviceAccount'
          serviceAccountToken: ${KUBERNETES_DEV_SA_TOKEN}
        - name: test
          url: ${KUBERNETES_TEST_URL}
          authProvider: 'serviceAccount'
          serviceAccountToken: ${KUBERNETES_TEST_SA_TOKEN}
        - name: stage
          url: ${KUBERNETES_STAGE_URL}
          authProvider: 'serviceAccount'
          serviceAccountToken: ${KUBERNETES_STAGE_SA_TOKEN}
        - name: prod
          url: ${KUBERNETES_PROD_URL}
          authProvider: 'serviceAccount'
          serviceAccountToken: ${KUBERNETES_PROD_SA_TOKEN}
        - name: sandbox
          url: ${KUBERNETES_SANDBOX_URL}
          authProvider: 'serviceAccount'
          serviceAccountToken: ${KUBERNETES_SANDBOX_SA_TOKEN}
        - name: ss-prod
          url: ${KUBERNETES_SS_PROD_URL}
          authProvider: 'serviceAccount'
          serviceAccountToken: ${KUBERNETES_SS_PROD_SA_TOKEN}