apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "44"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"backstage","namespace":"backstage-local"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"backstage"}},"template":{"metadata":{"labels":{"app":"backstage"}},"spec":{"containers":[{"env":[{"name":"APP_CONFIG_app_baseUrl","value":"http://localhost:7000"},{"name":"APP_CONFIG_backend_baseUrl","value":"http://localhost:7000"},{"name":"NODE_ENV","value":"development"}],"envFrom":[{"secretRef":{"name":"backstage-secrets"}}],"image":"ghcr.io/lijomadassery/backstage:latest","imagePullPolicy":"Always","livenessProbe":{"httpGet":{"path":"/healthcheck","port":7007},"initialDelaySeconds":60,"periodSeconds":10},"name":"backstage","ports":[{"containerPort":7007,"name":"http"}],"readinessProbe":{"httpGet":{"path":"/healthcheck","port":7007},"initialDelaySeconds":30,"periodSeconds":5},"resources":{"limits":{"cpu":"500m","memory":"1Gi"},"requests":{"cpu":"250m","memory":"512Mi"}},"volumeMounts":[{"mountPath":"/catalog/cdcr-teams.yaml","name":"catalog-teams","subPath":"cdcr-teams.yaml"},{"mountPath":"/catalog/coast-system.yaml","name":"catalog-coast","subPath":"coast-system.yaml"},{"mountPath":"/catalog/discharge-custody-check.yaml","name":"catalog-discharge","subPath":"discharge-custody-check.yaml"}]}],"serviceAccountName":"backstage","volumes":[{"configMap":{"name":"backstage-catalog"},"name":"catalog-teams"},{"configMap":{"name":"backstage-catalog-coast"},"name":"catalog-coast"},{"configMap":{"name":"backstage-catalog-discharge"},"name":"catalog-discharge"}]}}}}
  creationTimestamp: "2025-06-25T14:47:13Z"
  generation: 46
  labels:
    app: cdcr-development-portal
    backstage.io/kubernetes-id: cdcr-development-portal
  name: backstage
  namespace: backstage-local
  resourceVersion: "698690"
  uid: 92ac5841-61c7-455e-bcdc-cc61ea76d662
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cdcr-development-portal
      backstage.io/kubernetes-id: cdcr-development-portal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-07-02T13:43:11+05:30"
      creationTimestamp: null
      labels:
        app: cdcr-development-portal
        backstage.io/kubernetes-id: cdcr-development-portal
    spec:
      containers:
      - env:
        - name: APP_CONFIG_app_baseUrl
          value: http://127.0.0.1:7001
        - name: APP_CONFIG_backend_baseUrl
          value: http://127.0.0.1:7001
        - name: NODE_ENV
          value: development
        - name: APP_CONFIG_auth_enableExperimentalRedirectFlow
          value: "true"
        - name: APP_CONFIG_auth_providers_guest_dangerouslyAllowOutsideDevelopment
          value: "true"
        envFrom:
        - secretRef:
            name: backstage-secrets
        image: ghcr.io/lijomadassery/backstage:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 7007
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: backstage
        ports:
        - containerPort: 7007
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 7007
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /catalog/cdcr-teams.yaml
          name: catalog-teams
          subPath: cdcr-teams.yaml
        - mountPath: /catalog/coast-system.yaml
          name: catalog-coast
          subPath: coast-system.yaml
        - mountPath: /catalog/discharge-custody-check.yaml
          name: catalog-discharge
          subPath: discharge-custody-check.yaml
        - mountPath: /app/app-config.local.yaml
          name: app-config-local
          subPath: app-config.local.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: backstage
      serviceAccountName: backstage
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: backstage-catalog
        name: catalog-teams
      - configMap:
          defaultMode: 420
          name: backstage-catalog-coast
        name: catalog-coast
      - configMap:
          defaultMode: 420
          name: backstage-catalog-discharge
        name: catalog-discharge
      - configMap:
          defaultMode: 420
          name: backstage-app-config
        name: app-config-local
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-06-30T20:05:05Z"
    lastUpdateTime: "2025-07-02T08:13:47Z"
    message: ReplicaSet "backstage-785bdd5c7b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-07-02T08:19:26Z"
    lastUpdateTime: "2025-07-02T08:19:26Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 46
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
