apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: coast-ui
  title: COAST UI
  description: PWA frontend for COAST system that will replace existing PASS and CODP systems
  annotations:
    github.com/project-slug: CDCR-OMS-COAST/coast-ui
    backstage.io/source-location: url:https://github.com/CDCR-OMS-COAST/coast-ui
    backstage.io/techdocs-ref: dir:.
  tags:
    - pwa
    - frontend
    - coast
    - pass-replacement
    - codp-replacement
    - cdcr
  links:
    - url: https://github.com/CDCR-OMS-COAST/coast-ui
      title: Frontend Repository
      icon: github
spec:
  type: frontend
  lifecycle: development
  owner: cdcr-ams
  system: coast
  dependsOn:
    - component:coast-server
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: coast-server
  title: COAST Server
  description: Backend server for COAST system that will replace existing PASS and CODP systems
  annotations:
    github.com/project-slug: CDCR-OMS-COAST/coast-server
    backstage.io/source-location: url:https://github.com/CDCR-OMS-COAST/coast-server
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: coast-server
    backstage.io/kubernetes-namespace: coast
    backstage.io/kubernetes-label-selector: 'app=coast-server'
    flux.weave.works/git-repository: coast-server-gitrepo
    flux.weave.works/source: coast-server-source
  tags:
    - backend
    - server
    - coast
    - pass-replacement
    - codp-replacement
    - cdcr
    - api
  links:
    - url: https://github.com/CDCR-OMS-COAST/coast-server
      title: Backend Repository
      icon: github
spec:
  type: service
  lifecycle: development
  owner: cdcr-ams
  system: coast
  providesApis:
    - coast-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: coast-api
  title: COAST API
  description: API provided by COAST server for frontend integration
  tags:
    - api
    - coast
    - cdcr
spec:
  type: rest
  lifecycle: development
  owner: cdcr-ams
  system: coast
  definition: |
    openapi: 3.0.0
    info:
      title: COAST API
      description: API for COAST system replacing PASS and CODP
      version: 1.0.0
    paths:
      /health:
        get:
          summary: Health check endpoint
          responses:
            '200':
              description: Service is healthy
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: coast
  title: COAST System
  description: Comprehensive Offender Accountability System Technology - PWA solution replacing PASS and CODP systems
  tags:
    - pwa
    - replacement-system
    - pass
    - codp
    - cdcr
spec:
  owner: cdcr-ams
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: cdcr-ams
  description: CDCR Application Management Services Team
spec:
  type: team
  children: []