apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backstage

resources:
  - ../../base/namespace.yaml
  - ../../base/backstage-rbac.yaml
  - ../../base/network-policy.yaml
  - postgres.yaml
  - backstage-deployment.yaml

# Secrets should be created manually from secrets.yaml.example
# kubectl apply -f secrets.yaml (after copying and filling secrets.yaml.example)

# Note: In production, catalog data should come from git repos, not ConfigMaps