apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      serviceAccountName: backstage
      containers:
      - name: backstage
        image: ghcr.io/lijomadassery/backstage:1.0.7
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 7007
        envFrom:
        - secretRef:
            name: backstage-secrets
        env:
        - name: APP_CONFIG_app_baseUrl
          value: "http://127.0.0.1:7000"
        - name: APP_CONFIG_backend_baseUrl  
          value: "http://127.0.0.1:7000"
        - name: NODE_ENV
          value: development
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "backstage"
        - name: POSTGRES_PASSWORD
          value: "backstage123"
        args:
        - "node"
        - "packages/backend/dist/index.cjs.js"
        - "--config"
        - "app-config.yaml"
        - "--config"
        - "app-config.production.yaml"
        - "--config"
        - "app-config.local.yaml"
        # No proxy settings needed in minikube
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 7007
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 7007
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: catalog-teams
          mountPath: /catalog/cdcr-teams.yaml
          subPath: cdcr-teams.yaml
        - name: app-config-local
          mountPath: /app/app-config.local.yaml
          subPath: app-config.local.yaml
      volumes:
      - name: catalog-teams
        configMap:
          name: backstage-catalog
      - name: app-config-local
        configMap:
          name: backstage-app-config
---
apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: backstage-local
spec:
  selector:le
    app: backstage
  ports:
  - name: http
    port: 7000
    targetPort: 7007