apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-app-config
  namespace: backstage-local
data:
  app-config.local.yaml: |
    # Local override configuration for minikube deployment
    
    app:
      baseUrl: http://localhost:7000
      
    backend:
      baseUrl: http://localhost:7000
      cors:
        origin: http://localhost:7000
    
    # Local-only Kubernetes configuration - ONLY local minikube cluster
    kubernetes:
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: 'config'
          clusters:
            - name: local-minikube
              url: ${KUBERNETES_LOCAL_URL}
              authProvider: 'serviceAccount'
              serviceAccountToken: ${KUBERNETES_LOCAL_SA_TOKEN}
              skipTLSVerify: true
    
    # GitHub integration for your personal repos/CI-CD
    integrations:
      github:
        - host: github.com
          token: ${GITHUB_TOKEN}
          
    catalog:
      locations:
        # CDCR Teams and Users
        - type: file
          target: /catalog/cdcr-teams.yaml
          rules:
            - allow: [User, Group]
            
        # Backstage itself as a component
        - type: file
          target: /app/catalog-info.yaml
          rules:
            - allow: [Component, System, API]