apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-app-config
  namespace: backstage-local
data:
  app-config.local.yaml: |
    # Local override configuration for minikube deployment
    
    app:
      baseUrl: http://127.0.0.1:7001
      
    backend:
      baseUrl: http://127.0.0.1:7001
      cors:
        origin: http://127.0.0.1:7001
    
    # Local-only Kubernetes configuration - ONLY local minikube cluster
    kubernetes:
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: 'config'
          clusters:
            - name: local-minikube
              url: https://kubernetes.default.svc
              authProvider: 'serviceAccount'
              skipTLSVerify: true
              namespace: backstage-local
    
    # GitHub integration for your personal repos/CI-CD
    integrations:
      github:
        - host: github.com
          token: ${GITHUB_TOKEN}
          
    # Auth configuration for GitHub
    auth:
      providers:
        github:
          development:
            clientId: ${AUTH_GITHUB_CLIENT_ID}
            clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
            signIn:
              resolvers:
                # Use only username matching for now
                - resolver: usernameMatchingUserEntityName
          
    catalog:
      locations:
        # CDCR Teams and Users
        - type: file
          target: /catalog/cdcr-teams.yaml
          rules:
            - allow: [User, Group]
            
        # Backstage itself as a component
        - type: file
          target: /app/catalog-info.yaml
          rules:
            - allow: [Component, System, API]