# This is a template file - DO NOT commit actual secrets to git
# Create actual secrets using kubectl or your secret management system

apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
stringData:
  # GitHub Integration
  GITHUB_TOKEN: "your-github-token-here"
  AUTH_GITHUB_CLIENT_ID: "your-github-oauth-client-id"
  AUTH_GITHUB_CLIENT_SECRET: "your-github-oauth-client-secret"
  
  # Database
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "backstage"
  POSTGRES_PASSWORD: "your-secure-password-here"
  
  # Kubernetes Clusters (Service Account Tokens)
  KUBERNETES_DEV_URL: "https://your-dev-cluster-endpoint"
  KUBERNETES_DEV_SA_TOKEN: "your-dev-cluster-service-account-token"
  KUBERNETES_DEV_CA_DATA: "your-dev-cluster-ca-certificate-base64"
  
  KUBERNETES_TEST_URL: "https://your-test-cluster-endpoint"
  KUBERNETES_TEST_SA_TOKEN: "your-test-cluster-service-account-token"
  KUBERNETES_TEST_CA_DATA: "your-test-cluster-ca-certificate-base64"
  
  KUBERNETES_STAGE_URL: "https://your-stage-cluster-endpoint"
  KUBERNETES_STAGE_SA_TOKEN: "your-stage-cluster-service-account-token"
  KUBERNETES_STAGE_CA_DATA: "your-stage-cluster-ca-certificate-base64"
  
  KUBERNETES_PROD_URL: "https://your-prod-cluster-endpoint"
  KUBERNETES_PROD_SA_TOKEN: "your-prod-cluster-service-account-token"
  KUBERNETES_PROD_CA_DATA: "your-prod-cluster-ca-certificate-base64"
  
  KUBERNETES_SANDBOX_URL: "https://your-sandbox-cluster-endpoint"
  KUBERNETES_SANDBOX_SA_TOKEN: "your-sandbox-cluster-service-account-token"
  KUBERNETES_SANDBOX_CA_DATA: "your-sandbox-cluster-ca-certificate-base64"
  
  KUBERNETES_SS_PROD_URL: "https://your-ss-prod-cluster-endpoint"
  KUBERNETES_SS_PROD_SA_TOKEN: "your-ss-prod-cluster-service-account-token"
  KUBERNETES_SS_PROD_CA_DATA: "your-ss-prod-cluster-ca-certificate-base64"
  
  # ZScaler Proxy Configuration - Based on GitHub issue #29147
  # Only set HTTPS_PROXY to avoid 503 errors in corporate networks
  HTTPS_PROXY: "http://gateway.zscaler.net:80"
  NODE_TLS_REJECT_UNAUTHORIZED: "0"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: backstage
type: Opaque
stringData:
  POSTGRES_PASSWORD: "your-secure-postgres-password-here"