spec:
  template:
    spec:
      containers:
      - name: backstage
        volumeMounts:
        - name: catalog-teams
          mountPath: /catalog/cdcr-teams.yaml
          subPath: cdcr-teams.yaml
        - name: catalog-coast
          mountPath: /catalog/coast-system.yaml
          subPath: coast-system.yaml
        - name: catalog-discharge
          mountPath: /catalog/discharge-custody-check.yaml
          subPath: discharge-custody-check.yaml
      volumes:
      - name: catalog-teams
        configMap:
          name: backstage-catalog
      - name: catalog-coast
        configMap:
          name: backstage-catalog-coast
      - name: catalog-discharge
        configMap:
          name: backstage-catalog-discharge