apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-catalog
  namespace: backstage-local
data:
  cdcr-teams.yaml: |
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Group
    metadata:
      name: cdcr-platform-team
      description: CDCR Platform Engineering Team
    spec:
      type: team
      children: []
    ---
    apiVersion: backstage.io/v1alpha1
    kind: User
    metadata:
      name: lijo.madassery
      description: Platform Engineer
    spec:
      profile:
        displayName: Lijo Madassery
        email: lijo.madassery@cdcr.ca.gov
      memberOf: [cdcr-platform-team]
    ---
    apiVersion: backstage.io/v1alpha1
    kind: User
    metadata:
      name: john.doe
      description: Developer
    spec:
      profile:
        displayName: John Doe
        email: john.doe@cdcr.ca.gov
      memberOf: [cdcr-platform-team]
    ---
    apiVersion: backstage.io/v1alpha1
    kind: User
    metadata:
      name: jane.smith
      description: DevOps Engineer
    spec:
      profile:
        displayName: Jane Smith
        email: jane.smith@cdcr.ca.gov
      memberOf: [cdcr-platform-team]
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Group
    metadata:
      name: cdcr-dev-team
      description: CDCR Development Team
    spec:
      type: team
      children: []
    ---
    apiVersion: backstage.io/v1alpha1
    kind: User
    metadata:
      name: alice.johnson
      description: Senior Developer
    spec:
      profile:
        displayName: Alice Johnson
        email: alice.johnson@cdcr.ca.gov
      memberOf: [cdcr-dev-team]
    ---
    apiVersion: backstage.io/v1alpha1
    kind: User
    metadata:
      name: bob.wilson
      description: Full Stack Developer
    spec:
      profile:
        displayName: Bob Wilson
        email: bob.wilson@cdcr.ca.gov
      memberOf: [cdcr-dev-team]