site_name: '${{ values.name | title }}'
site_description: '${{ values.description }}'

nav:
  - Home: index.md
  - API Documentation: api.md
  - Deployment Guide: deployment.md
  - Troubleshooting: troubleshooting.md

plugins:
  - techdocs-core

theme:
  name: material
  palette:
    primary: 'blue'
    accent: 'green'